name: Validate PR Name

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr-name:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR title
        uses: actions/github-script@v6
        with:
          script: |
            const prTitle = context.payload.pull_request.title;

            // Validation regex:
            // ^CODE-: Ensures the string starts with "CODE-".
            // \d{2,4}: Matches between 2 and 4 digits.
            // : A single space is required after the digits.
            // [A-Z]: Ensures the first character after the space is an uppercase letter if it's alphabetic.
            const regex = /^CODE-\d{2,4} [A-Z]/;

            if (!regex.test(prTitle)) {
              core.setFailed("PR title must start with 'CODE-###', where ### is a number between 2 and 4 digits long.");
            } else {
              console.log("PR title validation succeeded.");
            }
